
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Dell
 */
public class manager_screen extends javax.swing.JFrame {

    /**
     * Creates new form manager_screen
     */
    public manager_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Manager_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Manager_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Manager_mail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Manager_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Sign_in = new javax.swing.JButton();
        Rest = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manager Registration");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Manager Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 99, -1, -1));
        jPanel2.add(Manager_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 124, 172, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Manager ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 182, -1, -1));

        Manager_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_idActionPerformed(evt);
            }
        });
        jPanel2.add(Manager_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 172, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Manager E-mail");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        Manager_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_mailActionPerformed(evt);
            }
        });
        jPanel2.add(Manager_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 172, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Manager mobile");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        Manager_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manager_phoneActionPerformed(evt);
            }
        });
        jPanel2.add(Manager_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("Manager Level");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        Sign_in.setBackground(new java.awt.Color(102, 255, 255));
        Sign_in.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sign_in.setText("Sign in");
        Sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_inActionPerformed(evt);
            }
        });
        jPanel2.add(Sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        Rest.setBackground(new java.awt.Color(102, 255, 255));
        Rest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rest.setText("Reset");
        Rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestActionPerformed(evt);
            }
        });
        jPanel2.add(Rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        Next.setBackground(new java.awt.Color(102, 255, 255));
        Next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel2.add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head", "supervisor", "Financial" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 110, -1));

        Back.setBackground(new java.awt.Color(102, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Manager registration.jpeg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 850, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manager_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_idActionPerformed

    private void Manager_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_mailActionPerformed

    private void Manager_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manager_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manager_phoneActionPerformed

    private void Sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_inActionPerformed
        if (Manager_id.getText().equals("") || Manager_mail.getText().equals("") || Manager_name.getText().equals("") || Manager_phone.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "This feild is required");
        } else {
            int ID = Integer.parseInt(Manager_id.getText());
            String Email = Manager_mail.getText();
            String Name = Manager_name.getText();
            int Mobile = Integer.parseInt(Manager_phone.getText());
            String selection = jComboBox1.getSelectedItem().toString();

            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
                Statement st = con.createStatement();
                String sql = "insert into manager (Manager_id,Manager_Name,Manager_email,Manager_mobile,Manager_level) values('" + ID + "','" + Email + "','" + Name + "','" + Mobile + "','" + selection + "')";
                st.executeUpdate(sql);

                // JOptionPane.showMessageDialog(this, "This field is required");
                Manager_id.setText("");
                Manager_mail.setText("");
                Manager_name.setText("");
                Manager_phone.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(manager_screen.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_Sign_inActionPerformed
    }
    private void RestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestActionPerformed
        int ID = Integer.parseInt(Manager_id.getText());

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
            Statement st = con.createStatement();
            String sql = "delete from admin WHERE User_id='" + ID + "'";
            st.executeUpdate(sql);

            Manager_id.setText("");
            Manager_mail.setText("");
            Manager_name.setText("");
            Manager_phone.setText("");
            } catch (SQLException ex) {
            Logger.getLogger(manager_screen.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_RestActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        this.setVisible(false);
        Registration r = new Registration();
        r.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
       this.setVisible(false);
        Tt f = new Tt();
        f.setVisible(true);
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Manager_id;
    private javax.swing.JTextField Manager_mail;
    private javax.swing.JTextField Manager_name;
    private javax.swing.JTextField Manager_phone;
    private javax.swing.JButton Next;
    private javax.swing.JButton Rest;
    private javax.swing.JButton Sign_in;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
