
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Medical_checkup extends javax.swing.JFrame {

    /**
     * Creates new form Medical_checkup
     */
    public Medical_checkup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rd_norm = new javax.swing.JRadioButton();
        rd_upnorm = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        no_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rd_pres = new javax.swing.JRadioButton();
        rd_tst = new javax.swing.JRadioButton();
        rd_bill = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        spin_mrn = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        spin_age = new javax.swing.JSpinner();
        btn_resm = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        check_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        doc_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        lab_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tech_txt = new javax.swing.JTextField();
        Insert_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        l_required = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2274, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Age:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 117, 38));

        name_txt.setBackground(new java.awt.Color(204, 204, 255));
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel2.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 424, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Full Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 41));

        rd_norm.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rd_norm);
        rd_norm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rd_norm.setForeground(new java.awt.Color(0, 0, 255));
        rd_norm.setText("Normal");
        rd_norm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_normActionPerformed(evt);
            }
        });
        jPanel2.add(rd_norm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        rd_upnorm.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rd_upnorm);
        rd_upnorm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rd_upnorm.setForeground(new java.awt.Color(0, 0, 255));
        rd_upnorm.setText("Upnormal");
        rd_upnorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_upnormActionPerformed(evt);
            }
        });
        jPanel2.add(rd_upnorm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Health Condition:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 38));

        no_txt.setBackground(new java.awt.Color(204, 204, 255));
        no_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_txtActionPerformed(evt);
            }
        });
        jPanel2.add(no_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 94, 22));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Type:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("NO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        rd_pres.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rd_pres);
        rd_pres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rd_pres.setForeground(new java.awt.Color(204, 0, 204));
        rd_pres.setText("Presicription");
        rd_pres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_presActionPerformed(evt);
            }
        });
        jPanel2.add(rd_pres, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 120, -1));

        rd_tst.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rd_tst);
        rd_tst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rd_tst.setForeground(new java.awt.Color(204, 0, 204));
        rd_tst.setText("Test");
        rd_tst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_tstActionPerformed(evt);
            }
        });
        jPanel2.add(rd_tst, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        rd_bill.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rd_bill);
        rd_bill.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rd_bill.setForeground(new java.awt.Color(204, 0, 204));
        rd_bill.setText("Bill");
        rd_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_billActionPerformed(evt);
            }
        });
        jPanel2.add(rd_bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Service:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 117, 38));

        spin_mrn.setModel(new javax.swing.SpinnerNumberModel(1, 0, 400, 1));
        jPanel2.add(spin_mrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 72, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("MRN:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 117, 38));

        spin_age.setModel(new javax.swing.SpinnerNumberModel(10, 10, 60, 1));
        jPanel2.add(spin_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 72, -1));

        btn_resm.setBackground(new java.awt.Color(255, 102, 102));
        btn_resm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_resm.setForeground(new java.awt.Color(51, 51, 255));
        btn_resm.setText("Reset");
        btn_resm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resmActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 145, -1));

        save_btn.setBackground(new java.awt.Color(255, 102, 102));
        save_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        save_btn.setForeground(new java.awt.Color(51, 51, 255));
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 128, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Medical Checkup");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        check_btn.setBackground(new java.awt.Color(255, 102, 102));
        check_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        check_btn.setForeground(new java.awt.Color(51, 51, 255));
        check_btn.setText("Check");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });
        jPanel2.add(check_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 128, -1));

        Back_btn.setBackground(new java.awt.Color(255, 102, 102));
        Back_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(51, 51, 255));
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 128, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Medical Checkup.jpeg"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 730, 450));

        jTabbedPane1.addTab("Checkup", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32500, -32578, 40, 14));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("Technician Name:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 197, -1));

        doc_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_txtActionPerformed(evt);
            }
        });
        jPanel5.add(doc_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 309, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Lab ID:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 90, 306, 0));

        lab_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_txtActionPerformed(evt);
            }
        });
        jPanel5.add(lab_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 306, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("Doctor Name:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 158, -1));

        tech_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tech_txtActionPerformed(evt);
            }
        });
        jPanel5.add(tech_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 309, -1));

        Insert_btn.setBackground(new java.awt.Color(255, 102, 204));
        Insert_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Insert_btn.setForeground(new java.awt.Color(51, 51, 255));
        Insert_btn.setText("Insert");
        Insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_btnActionPerformed(evt);
            }
        });
        jPanel5.add(Insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 151, -1));

        reset_btn.setBackground(new java.awt.Color(255, 102, 204));
        reset_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(51, 51, 255));
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel5.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 138, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Lab");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 140, -1));
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 81, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 820, 430));

        l_required.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        l_required.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(l_required, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 220, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Lab", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
       
        if (name_txt.getText().equals("") || rd_norm.getText().equals("") || no_txt.getText().equals("")||rd_bill.getText().equals("")||spin_mrn.getValue().equals("")||spin_age.getValue().equals(""))
        {
            JOptionPane.showMessageDialog(this, "This feild is required");
        }
        else 
        {
        String fname=name_txt.getText();
        String h_c=rd_norm.getText();
        int No=Integer.parseInt(no_txt.getText());
        String service=rd_bill.getText();
        String spin=spin_mrn.getValue().toString();
        String spin2=spin_age.getValue().toString();
       
           
            Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
             Statement stmt = con.createStatement();
            String sql="insert into Medicalcheckup (MRN,Full_Name,health_condition,service,age,Prescribtion,Lab_Lab_id) values('"+spin+"','"+fname+"','"+h_c+"','"+No+"','"+spin2+"','"+service+"','"+147852370+"')";
           int rowsInserted = stmt.executeUpdate(sql);
            if (rowsInserted > 0) {
           JOptionPane.showMessageDialog(this, "Inserted successfully");
            name_txt.setText("");
            String selection=null;
                if(rd_norm.isSelected())
                {
                selection="normal selected";
                }
                else{
                    selection="upnormal selected";
                }
            String selection1=null;
            if(rd_bill.isSelected())
                {
                selection1="bill selected";
                }
            else if(rd_tst.isSelected()){
                    selection1="test selected";
                }
            else{
            selection1="prescription selected";
            
            }
            no_txt.setText("");
            
           spin_mrn.setValue(1);
           spin_age.setValue(10);
            } 
           
        } catch (SQLException ex) {
            Logger.getLogger(Medical_checkup.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_save_btnActionPerformed
    }
    private void btn_resmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resmActionPerformed
         int mrn=Integer.parseInt(spin_mrn.getValue().toString());
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
             Statement st=con.createStatement();
          String sql = "delete from Medicalcheckup WHERE MRN='"+mrn+"'"; 
          int rowsDeleted = st.executeUpdate(sql);
           if (rowsDeleted> 0) {
          
             
            name_txt.setText("");
            String selection=null;
             if(rd_norm.isSelected())
              {
               selection="normal selected";
              }
             else{
               selection="upnormal selected";
              }
            no_txt.setText("");
            String selection1=null;
            if(rd_bill.isSelected())
                {
                selection1="bill selected";
                }
            else if(rd_tst.isSelected()){
                    selection1="test selected";
                }
            else{
            selection1="prescription selected";
            
            }
           spin_mrn.setValue(1);
           spin_age.setValue(10);
            }
            JOptionPane.showMessageDialog(null, "Deleted successfully");
        } catch (SQLException ex) {
            Logger.getLogger(Medical_checkup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_resmActionPerformed

    private void rd_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_billActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_billActionPerformed

    private void rd_tstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_tstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_tstActionPerformed

    private void rd_presActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_presActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_presActionPerformed

    private void no_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_txtActionPerformed

    private void rd_upnormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_upnormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_upnormActionPerformed

    private void rd_normActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_normActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_normActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void doc_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doc_txtActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void lab_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lab_txtActionPerformed

    private void tech_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tech_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tech_txtActionPerformed

    private void Insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_btnActionPerformed
        if (lab_txt.getText().equals("") || doc_txt.getText().equals("") || tech_txt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "This feild is required");
        }
        else 
        {
        int id=Integer.parseInt(lab_txt.getText());
        String doc_name=doc_txt.getText();
        String tech_name=tech_txt.getText();
        
        
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
            Statement st=con.createStatement();
            String sql="insert into Lab (Lab_id,Technician_Name,Doctor_Name) values('"+id+"','"+tech_name+"','"+doc_name+"')";
            st.executeUpdate(sql);
          
           
           lab_txt.setText("");
           doc_txt.setText("");
           tech_txt.setText("");
            
           this.setVisible(false);
           Schedule s=new Schedule();
           s.setVisible(true);
           
        
        } catch (SQLException ex) {
            Logger.getLogger(Medical_checkup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Insert_btnActionPerformed
}
    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
       
        int id=Integer.parseInt(lab_txt.getText());
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
             Statement st=con.createStatement();
          String sql = "delete from Lab WHERE Lab_id='"+id+"'"; 
          int rowsDeleted = st.executeUpdate(sql);
           if (rowsDeleted> 0) {
           JOptionPane.showMessageDialog(null, "Deleted successfully");
            } 
            lab_txt.setText("");
            doc_txt.setText("");
            tech_txt.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(Medical_checkup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_reset_btnActionPerformed

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        String fname=name_txt.getText();
       String spin2=spin_age.getValue().toString();
        
        
        try {
             boolean flag=false;
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
            Statement stmt = con.createStatement();
            String query="select Mem_Name, Mem_age from my_project.member";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
               
                String user_name = rs.getString("Mem_Name");
                String age = rs.getString("Mem_age");
                if(fname.equals(user_name) && spin2.equals(age))
                {
                    flag=true;
                    break;
                }

            }
            if(flag)
            {
              JOptionPane.showMessageDialog(this , "member is found ");  
            }
            else
            {
                JOptionPane.showMessageDialog(this , "Not found ");
                 name_txt.setText("");
                 spin_age.setValue(10);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_check_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        this.setVisible(false);
           mm n=new mm();
           n.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medical_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medical_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medical_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medical_checkup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medical_checkup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Insert_btn;
    private javax.swing.JButton btn_resm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton check_btn;
    private javax.swing.JTextField doc_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel l_required;
    private javax.swing.JTextField lab_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField no_txt;
    private javax.swing.JRadioButton rd_bill;
    private javax.swing.JRadioButton rd_norm;
    private javax.swing.JRadioButton rd_pres;
    private javax.swing.JRadioButton rd_tst;
    private javax.swing.JRadioButton rd_upnorm;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JSpinner spin_age;
    private javax.swing.JSpinner spin_mrn;
    private javax.swing.JTextField tech_txt;
    // End of variables declaration//GEN-END:variables
}
