

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;


/**
 *
 * @author RANA -1
 */
public class mm extends javax.swing.JFrame {

    /**
     * Creates new form mm
     */
    public mm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        c_id = new javax.swing.JTextField();
        c_email = new javax.swing.JTextField();
        c_age = new javax.swing.JTextField();
        c_mobile = new javax.swing.JTextField();
        c_address = new javax.swing.JTextField();
        c_DOB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        c_back = new javax.swing.JButton();
        c_register1 = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        c_reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Member Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 20));

        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        getContentPane().add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, -1));
        getContentPane().add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, -1));
        getContentPane().add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 200, -1));
        getContentPane().add(c_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, -1));
        getContentPane().add(c_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 200, -1));
        getContentPane().add(c_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 200, -1));
        getContentPane().add(c_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        c_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(c_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("E-mail");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Password");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Age");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Mobile");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("Address");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("Date of birth");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        c_back.setBackground(new java.awt.Color(204, 51, 0));
        c_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_back.setForeground(new java.awt.Color(255, 255, 255));
        c_back.setText("Back");
        c_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_backActionPerformed(evt);
            }
        });
        getContentPane().add(c_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, -1));

        c_register1.setBackground(new java.awt.Color(204, 51, 0));
        c_register1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_register1.setForeground(new java.awt.Color(255, 255, 255));
        c_register1.setText("R E G I S T E R");
        c_register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_register1ActionPerformed(evt);
            }
        });
        getContentPane().add(c_register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 200, 40));

        buttonGroup1.add(male);
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        c_reset.setBackground(new java.awt.Color(204, 51, 0));
        c_reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_reset.setForeground(new java.awt.Color(255, 255, 255));
        c_reset.setText("Reset");
        c_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_resetActionPerformed(evt);
            }
        });
        getContentPane().add(c_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Member Registration.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 470, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nameActionPerformed

    private void c_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_passwordActionPerformed

    private void c_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_backActionPerformed
       this.setVisible(false);
       Tt p=new Tt();
       p.setVisible(true);
                                           
    }//GEN-LAST:event_c_backActionPerformed

    private void c_register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_register1ActionPerformed
if (c_name.getText().equals("") || c_id.getText().equals("") || c_email.getText().equals("")||c_password.getPassword().equals("")||c_age.getText().equals("")||c_mobile.getText().equals("")||c_address.getText().equals("")||c_DOB.getText().equals("")||male.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "This feild is required");
        }
        else 
        {

        int id = Integer.parseInt(c_id.getText());
        String name = c_name.getText();
        String address = c_address.getText();
        int age = Integer.parseInt(c_age.getText());
        int mobile = Integer.parseInt(c_mobile.getText());
        String DOB = c_DOB.getText();
        String gender = male.getText();
        //String feMale = female.getText();
        int password = Integer.parseInt(c_password.getText());
        String email = c_email.getText();
        
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root","root123");
            Statement st = con.createStatement();
            String sql ="insert into member(Mem_id, Mem_Name , Mem_address , Mem_age , Mem_mobile , Mem_DOB ,Mem_gender , Mem_password , Mem_email,Admin_User_id,Payment_gateway_Regesteration_No) values ('"+id+"','"+name+"','"+address+"','"+age+"','"+mobile+"','"+DOB+"','"+gender+"','"+password+"','"+email+"','"+123456+"','"+10+"') ";
            int rowInserted = st.executeUpdate(sql);
            if (rowInserted > 0){
                
                c_name.setText("");
                c_id.setText("");
                c_address.setText("");
                c_age.setText("");
                c_mobile.setText("");
                c_DOB.setText("");
                String selection=null;
                if(male.isSelected())
                {
                selection="Male selected";
                }
                else{
                    selection="feMale selected";
                }
                
                c_password.setText("");
                c_email.setText("");
           this.setVisible(false);
           Medical_checkup s=new Medical_checkup();
           s.setVisible(true);
            }
            
            
        }catch (SQLException ex){
            Logger.getLogger(mm.class.getName()).log(Level.SEVERE,null,ex);
            
        }
    
    }//GEN-LAST:event_c_register1ActionPerformed
    }
    private void c_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_resetActionPerformed
        int id=Integer.parseInt(c_id.getText());
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
             java.sql.Statement st=con.createStatement();
          String sql = "delete from Member WHERE Mem_id='"+id+"'"; 
          int rowsDeleted = st.executeUpdate(sql);
           if (rowsDeleted> 0) {
           JOptionPane.showMessageDialog(null, "Deleted successfully");
            } 
            c_name.setText("");
            c_id.setText("");
            c_email.setText("");
            c_password.setText("");
            c_age.setText("");
            c_mobile.setText("");
            c_address.setText("");
            c_DOB.setText("");
        } catch (SQLException ex) {

    }//GEN-LAST:event_c_resetActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField c_DOB;
    private javax.swing.JTextField c_address;
    private javax.swing.JTextField c_age;
    private javax.swing.JButton c_back;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_mobile;
    private javax.swing.JTextField c_name;
    private javax.swing.JPasswordField c_password;
    private javax.swing.JButton c_register1;
    private javax.swing.JButton c_reset;
    private javax.swing.JRadioButton female;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton male;
    // End of variables declaration//GEN-END:variables

    private static class JOtionPane {

        private static void showMessageDialog(mm aThis, String inserted_successfully) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public JOtionPane() {
        }
    }
}
