/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author RANA -1
 */
public class Tt extends javax.swing.JFrame {

    /**
     * Creates new form Tt
     */
    public Tt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        c_id = new javax.swing.JTextField();
        c_email = new javax.swing.JTextField();
        c_mobile = new javax.swing.JTextField();
        c_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c_register = new javax.swing.JButton();
        c_back = new javax.swing.JButton();
        c_reset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trainer Enrolment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 310, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        c_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nameActionPerformed(evt);
            }
        });
        jPanel1.add(c_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 190, 30));
        jPanel1.add(c_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 190, -1));
        jPanel1.add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 190, -1));
        jPanel1.add(c_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 190, -1));
        jPanel1.add(c_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("E-mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Mobile");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        c_register.setBackground(new java.awt.Color(255, 153, 0));
        c_register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_register.setForeground(new java.awt.Color(255, 255, 255));
        c_register.setText("E N R O L L");
        c_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_registerActionPerformed(evt);
            }
        });
        jPanel1.add(c_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        c_back.setBackground(new java.awt.Color(255, 153, 0));
        c_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_back.setForeground(new java.awt.Color(255, 255, 255));
        c_back.setText("Back");
        c_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_backActionPerformed(evt);
            }
        });
        jPanel1.add(c_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 90, -1));

        c_reset.setBackground(new java.awt.Color(255, 153, 0));
        c_reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c_reset.setForeground(new java.awt.Color(255, 255, 255));
        c_reset.setText("Reset");
        c_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_resetActionPerformed(evt);
            }
        });
        jPanel1.add(c_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 90, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Trainer Enrolment.jpeg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nameActionPerformed
        
    }//GEN-LAST:event_c_nameActionPerformed

    private void c_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_registerActionPerformed
       if (c_name.getText().equals("") || c_id.getText().equals("") || c_email.getText().equals("")||c_mobile.getText().equals("")||c_address.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "This feild is required");
        }
        else 
        {

        int id = Integer.parseInt(c_id.getText());
        String name = c_name.getText();
        String address = c_address.getText();
        int mobile = Integer.parseInt(c_mobile.getText());
        String email = c_email.getText();
        
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root","root123");
            java.sql.Statement st1 = con.createStatement();
            String sql ="insert into trainer (Trainer_Name , Trainer_address , Trainer_mobile , Trainer_email,Admin_User_id) values ('"+name+"','"+address+"','"+mobile+"','"+email+"','"+56789+"') ";
            
            int rowInserted=st1.executeUpdate(sql);
            if (rowInserted > 0){
                JOptionPane.showMessageDialog(this,"Inserted successfully");
                c_name.setText("");
                c_id.setText("");
                c_address.setText("");
                c_mobile.setText("");
                c_email.setText("");
          this.setVisible(false);
          mm l = new mm ();
          l.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "failed");
            }
            
        }catch (SQLException ex){
            Logger.getLogger(Tt.class.getName()).log(Level.SEVERE,null,ex);
            
        }

    }//GEN-LAST:event_c_registerActionPerformed
    }
    private void c_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_backActionPerformed
          this.setVisible(false);
          manager_screen M = new manager_screen();
          M.setVisible(true);
    }//GEN-LAST:event_c_backActionPerformed

    private void c_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_resetActionPerformed
                int id=Integer.parseInt(c_id.getText());
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/my_project?autoReconnect=true&useSSL=false", "root", "root123");
             java.sql.Statement st=con.createStatement();
          String sql = "delete from Trainer WHERE Trainer_id='"+id+"'"; 
          int rowsDeleted = st.executeUpdate(sql);
           if (rowsDeleted> 0) {
           JOptionPane.showMessageDialog(null, "Deleted successfully");
            } 
            c_name.setText("");
            c_id.setText("");
            c_email.setText("");
            c_mobile.setText("");
            c_address.setText("");  
        } catch (SQLException ex) {
            Logger.getLogger(Medical_checkup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_c_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_address;
    private javax.swing.JButton c_back;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_id;
    private javax.swing.JTextField c_mobile;
    private javax.swing.JTextField c_name;
    private javax.swing.JButton c_register;
    private javax.swing.JButton c_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
